<fieldset>
    <legend>Files list</legend>
    <?php
    if (! isset($this->files) || count($this->files) === 0): ?>
        <div class="alert alert-warning text-center">
            Files dir is empty
        </div><?php
    else: ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Extension</th>
                    <th>Size</th>
                </tr>
            </thead>
            <tbody><?php
                /** @var SplFileInfo $file */
                foreach ($this->files as $file): ?>
                    <tr>
                        <td><?php echo $file->getBasename() ?></td>
                        <td><?php echo $file->getExtension() ?></td>
                        <td><?php echo $file->getSize() ?></td>
                    </tr><?php
                endforeach; ?>
            </tbody>
        </table><?php
    endif;
    ?>
</fieldset>
<fieldset>
    <legend>Upload new files</legend>
    <form name="uploadFiles" id="uploadFiles" method="post"
          action="<?php echo $this->url('home/upload-files') ?>" enctype="multipart/form-data">
        <input type="file" name="files[]" multiple>
        <button type="submit" class="btn btn-primary">Upload files</button>
    </form>
</fieldset>
